AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CreateThumbnail:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.js
      Runtime: nodejs12.x
      Timeout: 60
      Policies: AWSLambdaExecute
      Events:
        CreateThumbnailEvent:
          Type: S3
          Properties:
            Bucket: !Ref SrcBucket
            Events: s3:ObjectCreated:*
Resources:
  SrcBucket:
    Type: 'AWS::S3::Bucket'
  DstBucket:
    Type: 'AWS::S3::Bucket'
    DependsOn: SrcBucket
    Properties:
      BucketName: !Join
        - ''
        - - !Ref SrcBucket
          - '-resized'
